version: '3.1'

services:
  app:
    image: 'music-feed-platform:1.0'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music-feed-platform
    volumes:
      - media-storage:/media
      - logs:/logs
    ports:
      - 8000:8000
      - 5005:5005
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/musicfeed-platform
      - SPRING_DATASOURCE_USERNAME=${DB_APPLICATION_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_APPLICATION_PASSWORD}

volumes:
  media-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$PWD/media"
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$PWD/logs"